<a href="https://colab.research.google.com/github/masagun-unughaid/masagun-unughaid/blob/main/Copy_of_KNNRegresi_explained.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**KNN untuk permasalahan Regresi**

sumber : https://www.tutorialspoint.com/machine_learning_with_python/machine_learning_with_python_knn_algorithm_finding_nearest_neighbors.htm



import library

In [1]:
import numpy as np
import pandas as pd

Dowload dataset 



In [2]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/concrete/slump/slump_test.data"
headernames = ['id', 'label', 'time', 'petal-width', 'Class']
data = pd.read_csv(url)
array = data.values
X = array[:,1:10]
Y = array[:,10]
data.shape


(103, 11)

tamplikan data, X dan y 

In [3]:
data.head(3)

No  Cement   Slag  ...  SLUMP(cm)  FLOW(cm)  Compressive Strength (28-day)(Mpa)
0   1   273.0   82.0  ...       23.0      62.0                               34.99
1   2   163.0  149.0  ...        0.0      20.0                               41.14
2   3   162.0  148.0  ...        1.0      20.0                               41.81

[3 rows x 11 columns]

In [4]:
X[0:9,:]

array([[273. ,  82. , 105. , 210. ,   9. , 904. , 680. ,  23. ,  62. ],
       [163. , 149. , 191. , 180. ,  12. , 843. , 746. ,   0. ,  20. ],
       [162. , 148. , 191. , 179. ,  16. , 840. , 743. ,   1. ,  20. ],
       [162. , 148. , 190. , 179. ,  19. , 838. , 741. ,   3. ,  21.5],
       [154. , 112. , 144. , 220. ,  10. , 923. , 658. ,  20. ,  64. ],
       [147. ,  89. , 115. , 202. ,   9. , 860. , 829. ,  23. ,  55. ],
       [152. , 139. , 178. , 168. ,  18. , 944. , 695. ,   0. ,  20. ],
       [145. ,   0. , 227. , 240. ,   6. , 750. , 853. ,  14.5,  58.5],
       [152. ,   0. , 237. , 204. ,   6. , 785. , 892. ,  15.5,  51. ]])

In [5]:
Y[0:3]

array([34.99, 41.14, 41.81])

  Bagi data menjadi 60 % training dan 40% testing 
  

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.40)

Misalkan y = yang harus diperkirakan adalah "Compressive Strength (28-day)(Mpa)" 

masukan X ADALAH KOLOM : Cement,Slag,Fly ash,Water,SP,Coarse Aggr.,Fine Aggr.,SLUMP(cm),FLOW(cm)

Kita akan menggunakan KNN untuk melakukan regresi dengan mengimport library KNN regresi sebagai berikut 


In [7]:
from sklearn.neighbors import KNeighborsRegressor
knnr = KNeighborsRegressor(n_neighbors = 10)
knnr.fit(X_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                    weights='uniform')

Menampilkan error y hasil prediksi 

dan y test 

In [8]:
y_predict = knnr.predict(X_test)
y_predict



array([35.306, 32.374, 33.833, 33.968, 43.976, 42.142, 39.224, 37.003,
       30.447, 42.757, 39.706, 28.118, 38.06 , 41.071, 34.53 , 31.958,
       32.506, 31.958, 42.757, 32.748, 43.855, 35.183, 35.426, 33.645,
       42.435, 30.714, 42.141, 34.689, 36.12 , 34.757, 41.513, 43.507,
       43.187, 34.757, 35.96 , 34.757, 43.226, 42.757, 40.268, 43.373,
       36.857, 30.447])

In [9]:
y_test

array([26.42, 33.38, 38.46, 34.45, 48.77, 36.19, 32.84, 38.19, 31.77,
       41.14, 35.52, 17.19, 37.39, 32.71, 33.51, 30.97, 33.78, 35.39,
       45.69, 30.43, 38.46, 32.44, 26.82, 27.89, 41.27, 29.63, 49.97,
       35.52, 34.99, 41.81, 42.08, 38.59, 44.08, 41.14, 43.54, 42.08,
       58.53, 45.82, 39.93, 52.65, 38.86, 18.26])

Menampilkan Mean square Error 

In [10]:
print ("The MSE is:",format(np.power(y_test-y_predict,2).mean()))

The MSE is: 32.429148428571445
